name: Fork Synchronization
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: aws-ia
          base: main
          head: main
          retry_after: 10
          auto_merge: false
